/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-03 18:28:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Railway Reservation System</title>\r\n");
      out.write("<style>* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the header */\r\n");
      out.write("header {\r\n");
      out.write("  background-color: #666;\r\n");
      out.write("  padding: 30px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-size: 35px;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Create two columns/boxes that floats next to each other */\r\n");
      out.write("nav {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 30%;\r\n");
      out.write("  height: 300px; /* only for demonstration, should be removed */\r\n");
      out.write("  background: #ccc;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the list inside the menu */\r\n");
      out.write("nav ul {\r\n");
      out.write("  list-style-type: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("article {\r\n");
      out.write("  float: left;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  width: 70%;\r\n");
      out.write("  background-color: #f1f1f1;\r\n");
      out.write("  height: 300px; /* only for demonstration, should be removed */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Clear floats after the columns */\r\n");
      out.write("section:after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: table;\r\n");
      out.write("  clear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the footer */\r\n");
      out.write("footer {\r\n");
      out.write("  background-color: #777;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */\r\n");
      out.write("@media (max-width: 600px) {\r\n");
      out.write("  nav, article {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("  }\r\n");
      out.write("}</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h2>1. About Online Reservation</h2>\r\n");
      out.write("<p>The Indian railway website, IRCTC is the most traffic-filled site. The tickets are usually booked through this official site. If you are planning to book tickets the day before your departure date, tatkal tickets are available from 10:00 AM and ends as soon as the tickets are booked. The tickets are limited and the demand will be sky-high. If you are able to reserve a ticket through tatkal, you can get berth seats. Cancellation of tatkal ticket will not be refunded. Anyone can reserve tickets through IRCTC. You can pay through debit card, credit card, international card and others.\r\n");
      out.write("</p>\r\n");
      out.write("<p>\r\n");
      out.write("On the other hand, you can choose tour portals to reserve tickets. The sites will be faster and user-friendly. Not all trains will be displayed in such portals and a small fee will be levied as service charge. A foreigner can also book tickets through an account that will be verified through and Indian mobile number or by mailing passport details to IRCTC. Foreigners can easily book train tickets through tour portals.</p>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("  <h2>Online Railway Reservation System</h2>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("  <nav>\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li><a href=\"#\">Home</a></li><br>\r\n");
      out.write("      <li><a href=\"#\">About</a></li><br>\r\n");
      out.write("      <li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("  \r\n");
      out.write("  <article>\r\n");
      out.write("    <h1>2. Online Reservation</h1>\r\n");
      out.write("    <p>Following are the steps involved in online booking of train tickets:\r\n");
      out.write("Visit IRCTC and log into the site. If you are new member, it will request you to sign up.\r\n");
      out.write("</p>\r\n");
      out.write("    <p>Once you log into the site, there will be tab named âPlan My Journeyâ. Enter the details of the station of departure and station of arrival. You will have to enter details like the class of ticket you are preferring, journey date and others. Select the option for e-ticket. Keep the class and type of train open to find availability during tourism season and festival times.</p>\r\n");
      out.write("    <p>If you have given wrong station name or if there is no availability of trains, you will get an error message. Else, a tabular column of available train, departure time and arrival time will be listed. You can click on the train to check the train fare, availability of berth and others.\r\n");
      out.write("</p>\r\n");
      out.write("<p>If there is availability of train or you want to book the tickets there will be option to book now. Just click on the book now button and you fill find a form of Journey Details. Fill the journey details like Name, Age, Gender, Berth Preference, Nationality, ID Card Type and ID Card No.</p>\r\n");
      out.write("  </article>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
