/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-03 16:31:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"Register.css\">\r\n");
      out.write("<title>User Registration</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"topnav\">\r\n");
      out.write("  <a  href=\"home.html\">Home</a>\r\n");
      out.write("  <a href=\"\">About</a>\r\n");
      out.write("  <a href=\"\">Contact</a>\r\n");
      out.write("  <a href=\"\">Review</a>\r\n");
      out.write("  </div><br><br>\r\n");
      out.write("<form action=\"RegisterController\" method=\"get\" style=\"max-width:500px;margin:auto\" >\r\n");
      out.write(" <input type=\"hidden\" name=\"action\" value=\"insert\"/> \r\n");
      out.write("  <h2 align=\"center\">Registration Form</h2><hr>\r\n");
      out.write("  <div class=\"input-container\">\r\n");
      out.write("    <i class=\"fa fa-user icon\"></i>\r\n");
      out.write("    <input class=\"input-field\" type=\"text\" placeholder=\"User ID\" name=\"userid\">\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("   <div class=\"input-container\">\r\n");
      out.write("    <i class=\"fa fa-key icon\"></i>\r\n");
      out.write("    <input class=\"input-field\" type=\"password\" placeholder=\"Password\" name=\"password\">\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- <div class=\"input-container\">\r\n");
      out.write("    <i class=\"fa fa-key icon\"></i>\r\n");
      out.write("    <input class=\"input-field\" type=\"password\" placeholder=\"Re-Enter Password\" name=\"rpassword\">\r\n");
      out.write("  </div>\r\n");
      out.write("  -->\r\n");
      out.write("\r\n");
      out.write("<h4 Style=\"background-color:gray;\">Persional Detail</h4>\r\n");
      out.write("  <div class=\"input-container\">\r\n");
      out.write("    <i class=\"fa fa-user icon\"></i>\r\n");
      out.write("    <input class=\"input-field\" type=\"text\" placeholder=\"First Name\" name=\"firstname\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"input-container\">\r\n");
      out.write("    <i class=\"fa fa-user icon\"></i>\r\n");
      out.write("    <input class=\"input-field\" type=\"text\" placeholder=\"Middle name\" name=\"middlename\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"input-container\">\r\n");
      out.write("    <i class=\"fa fa-user icon\"></i>\r\n");
      out.write("    <input class=\"input-field\" type=\"text\" placeholder=\"Last name\" name=\"lastname\">\r\n");
      out.write("  </div>\r\n");
      out.write(" <div> GENDER :<input type=\"radio\" name=\"gender\" value=\"male\" checked> Male\r\n");
      out.write("  <input type=\"radio\" name=\"gender\" value=\"female\"> Female<br><br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div> MARITIAL STATUS :<input type=\"radio\" name=\"status\" value=\"Married\" checked> Married\r\n");
      out.write("  <input type=\"radio\" name=\"status\" value=\"Unmarried\"> Unmarried<br><br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("Date Of Birth: <input type=\"date\" name=\"dob\"><br><br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"input-container\">\r\n");
      out.write("    <i class=\"fa fa-envelope icon\"></i>\r\n");
      out.write("    <input class=\"input-field\" type=\"text\" placeholder=\"Adhar Card No\" name=\"adhaarcard\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"input-container\">\r\n");
      out.write("    <i class=\"fa fa-envelope icon\"></i>\r\n");
      out.write("    <input class=\"input-field\" type=\"text\" placeholder=\"Pan Crad No\" name=\"pancard\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"input-container\">\r\n");
      out.write("    <i class=\"fa fa-envelope icon\"></i>\r\n");
      out.write("    <input class=\"input-field\" type=\"text\" placeholder=\"Email\" name=\"email\">\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("<div class=\"input-container\">\r\n");
      out.write("    <i class=\"fa fa-phone icon\"></i>\r\n");
      out.write("    <input class=\"input-field\" type=\"text\" placeholder=\"Mobile Number\" name=\"mobileno\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div> NATIONALITY :<input type=\"radio\" name=\"nationality\" value=\"Indian\" checked> Indian\r\n");
      out.write("  <input type=\"radio\" name=\"nationality\" value=\"other\"> Other<br><br>\r\n");
      out.write("</div>\r\n");
      out.write("<h4 Style=\"background-color:gray;\">Residential Address</h4>\r\n");
      out.write("\r\n");
      out.write("<textarea rows=\"4\" cols=\"60\" name=\"address\" placeholder=\"Enter your Address\">\r\n");
      out.write("</textarea> <br><br>\r\n");
      out.write(" <!-- <label>\r\n");
      out.write("      <input type=\"checkbox\" checked=\"checked\" name=\"remember\" style=\"margin-bottom:15px\"> Remember me\r\n");
      out.write("    </label>-->\r\n");
      out.write("<hr>\r\n");
      out.write("  <p align=\"center\">By creating an account you agree to our <a href=\"#\" style=\"color:dodgerblue\">Terms & Privacy</a>.</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <input type=\"submit\" class=\"btn\" value=\"Registration\"/><br/>\r\n");
      out.write("\r\n");
      out.write("  <p align=\"center\">Already have an account? <a href=\"login.jsp\" style=\"color:dodgerblue\">Sign in</a>.</p>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
